FROM python:3.11-slim

WORKDIR /app

ENV PYTHONPATH=/app:$PYTHONPATH

RUN pip install --upgrade pip setuptools wheel

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . src/

CMD ["celery", "-A", "src.worker.celery_app", "worker", "--loglevel=info", "--concurrency=4"]